### ISSUE TITLE
Project status 

### ISSUE THREAD

**Issue by amon-ra** [redneb/hubic-auth-swift#1]
I have tested the release and works ok.
What changes have you included since this release?
Can you post a new release with this  changes?

Great work!

**Comment by redneb** [comment]
Hi,

The only change I've made since the last release, was to create a (haskell) library, move all the code there, and turn the executable into a thin wrapper around that library. So there wasn't any new functionality introduced for the executable, which is why I haven't made a new release.

**Comment by amon-ra** [comment]
Ok thanks
